#!/bin/bash
OLD=${PWD}
CURRENT_SCRIPT_PATH=$0
PROJECT_PATH="$(dirname "${CURRENT_SCRIPT_PATH}")"
PROJECT_NAME=${PROJECT_PATH##*/}
PROJECT_BUILD_PATH="${PROJECT_PATH}/../${PROJECT_NAME}Build"

mkdir -p ${PROJECT_BUILD_PATH}
cd ${PROJECT_BUILD_PATH}
cmake -G Xcode ${PROJECT_PATH}
cd ${OLD}